-- 幂等刷新现有用户与角色表的表注释和字段注释。
ALTER TABLE manga_user
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '用户主键',
    MODIFY COLUMN username VARCHAR(64) NOT NULL COMMENT '登录用户名',
    MODIFY COLUMN password_hash VARCHAR(100) NULL COMMENT '账号密码摘要，第三方登录账号可为空',
    MODIFY COLUMN display_name VARCHAR(64) NOT NULL COMMENT '用户显示名称',
    MODIFY COLUMN status VARCHAR(20) NOT NULL COMMENT '账号状态',
    MODIFY COLUMN registration_source VARCHAR(32) NOT NULL DEFAULT 'PASSWORD' COMMENT '账号初始注册来源',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
    MODIFY COLUMN created_by VARCHAR(64) NOT NULL COMMENT '创建人标识',
    MODIFY COLUMN updated_by VARCHAR(64) NOT NULL COMMENT '最后修改人标识',
    COMMENT = '平台用户表';

ALTER TABLE manga_role
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '角色主键',
    MODIFY COLUMN code VARCHAR(32) NOT NULL COMMENT '角色编码',
    MODIFY COLUMN name VARCHAR(64) NOT NULL COMMENT '角色名称',
    MODIFY COLUMN description VARCHAR(255) NOT NULL COMMENT '角色用途说明',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
    MODIFY COLUMN created_by VARCHAR(64) NOT NULL COMMENT '创建人标识',
    MODIFY COLUMN updated_by VARCHAR(64) NOT NULL COMMENT '最后修改人标识',
    COMMENT = '平台角色表';

ALTER TABLE manga_user_role
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户主键',
    MODIFY COLUMN role_id BIGINT NOT NULL COMMENT '角色主键',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
    MODIFY COLUMN created_by VARCHAR(64) NOT NULL COMMENT '创建人标识',
    MODIFY COLUMN updated_by VARCHAR(64) NOT NULL COMMENT '最后修改人标识',
    COMMENT = '用户角色关联表';

ALTER TABLE manga_user_identity
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '外部身份主键',
    MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '平台用户主键',
    MODIFY COLUMN provider VARCHAR(32) NOT NULL COMMENT '外部身份提供方',
    MODIFY COLUMN provider_user_id VARCHAR(128) NOT NULL COMMENT '提供方内用户唯一标识',
    MODIFY COLUMN provider_union_id VARCHAR(128) NULL COMMENT '提供方跨应用统一用户标识',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
    MODIFY COLUMN created_by VARCHAR(64) NOT NULL COMMENT '创建人标识',
    MODIFY COLUMN updated_by VARCHAR(64) NOT NULL COMMENT '最后修改人标识',
    COMMENT = '用户外部登录身份表';

ALTER TABLE manga_external_login_session
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '外部登录会话主键',
    MODIFY COLUMN login_token CHAR(36) NOT NULL COMMENT '浏览器轮询使用的一次性登录令牌',
    MODIFY COLUMN provider VARCHAR(32) NOT NULL COMMENT '外部身份提供方',
    MODIFY COLUMN provider_scene_key VARCHAR(64) NOT NULL COMMENT '提供方二维码场景标识',
    MODIFY COLUMN provider_ticket VARCHAR(512) NOT NULL COMMENT '提供方返回的二维码票据',
    MODIFY COLUMN provider_qr_url VARCHAR(1024) NOT NULL COMMENT '二维码展示地址',
    MODIFY COLUMN status VARCHAR(20) NOT NULL COMMENT '外部登录会话状态',
    MODIFY COLUMN user_id BIGINT NULL COMMENT '扫码确认后的平台用户主键',
    MODIFY COLUMN expires_at TIMESTAMP NOT NULL COMMENT '登录会话过期时间',
    MODIFY COLUMN consumed_at TIMESTAMP NULL COMMENT '登录令牌兑换时间',
    MODIFY COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
    MODIFY COLUMN created_by VARCHAR(64) NOT NULL COMMENT '创建人标识',
    MODIFY COLUMN updated_by VARCHAR(64) NOT NULL COMMENT '最后修改人标识',
    COMMENT = '外部扫码登录会话表';
