CREATE TABLE manga_creative_conversation (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '创作会话数据库主键',
    conversation_id CHAR(36) NOT NULL COMMENT '创作会话唯一标识',
    user_id BIGINT NOT NULL COMMENT '会话所属用户主键',
    project_id BIGINT NULL COMMENT '可选的绑定项目主键',
    title VARCHAR(160) NOT NULL COMMENT '会话标题',
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '会话状态',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录最后更新时间',
    created_by VARCHAR(128) NOT NULL DEFAULT 'system:database-migration' COMMENT '记录创建操作者',
    updated_by VARCHAR(128) NOT NULL DEFAULT 'system:database-migration' COMMENT '记录最后更新操作者',
    PRIMARY KEY (id),
    CONSTRAINT uk_manga_creative_conversation_id UNIQUE (conversation_id),
    CONSTRAINT ck_manga_creative_conversation_status CHECK (status IN ('ACTIVE')),
    INDEX idx_manga_creative_conversation_user_updated (user_id, updated_at),
    INDEX idx_manga_creative_conversation_project_updated (project_id, updated_at),
    CONSTRAINT fk_manga_creative_conversation_user FOREIGN KEY (user_id) REFERENCES manga_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_manga_creative_conversation_project FOREIGN KEY (project_id) REFERENCES manga_project (id) ON DELETE SET NULL
) COMMENT = 'AI 漫剧创作会话表';

CREATE TABLE manga_creative_run (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '创作运行数据库主键',
    run_id CHAR(36) NOT NULL COMMENT '创作运行唯一标识',
    request_id VARCHAR(64) NOT NULL COMMENT '用户维度启动幂等标识',
    request_fingerprint CHAR(64) NOT NULL COMMENT '启动请求语义的 SHA-256 指纹',
    conversation_id CHAR(36) NULL COMMENT '可选的所属会话标识，手动触发时为空',
    user_id BIGINT NOT NULL COMMENT '发起用户主键',
    project_id BIGINT NULL COMMENT '运行绑定项目主键',
    trigger_source VARCHAR(32) NOT NULL COMMENT '运行触发来源：CONVERSATION 或 MANUAL',
    operation_type VARCHAR(64) NOT NULL COMMENT '本次运行执行的稳定业务操作类型',
    target_type VARCHAR(32) NULL COMMENT '可选的直接目标资源类型',
    target_id BIGINT NULL COMMENT '可选的直接目标资源主键',
    engine_version VARCHAR(64) NOT NULL COMMENT '创建时固化的执行引擎版本',
    workflow_type VARCHAR(64) NOT NULL COMMENT '创建时固化的工作流类型',
    workflow_version VARCHAR(64) NOT NULL COMMENT '创建时固化的工作流版本',
    permission_policy VARCHAR(32) NOT NULL COMMENT '创建时固化的 Agent 权限策略',
    budget_json LONGTEXT NULL COMMENT '可选的运行预算和资源限制快照',
    status VARCHAR(32) NOT NULL COMMENT '运行聚合状态',
    active_conversation_id CHAR(36) NULL COMMENT '仅活跃会话 Run 使用的并发唯一键',
    owner_instance_id VARCHAR(128) NULL COMMENT '当前执行器实例标识',
    owner_epoch BIGINT NOT NULL DEFAULT 0 COMMENT '执行器租约代次',
    lease_until TIMESTAMP NULL COMMENT '执行器租约截止时间',
    deadline_at TIMESTAMP NOT NULL COMMENT '运行允许执行的最晚时间',
    next_sequence BIGINT NOT NULL DEFAULT 1 COMMENT '下一个事件序号',
    terminal_sequence BIGINT NULL COMMENT '唯一终态事件序号',
    cancel_requested_at TIMESTAMP NULL COMMENT '首次收到取消请求的时间',
    started_at TIMESTAMP NULL COMMENT '实际开始执行时间',
    finished_at TIMESTAMP NULL COMMENT '进入终态时间',
    error_code VARCHAR(64) NULL COMMENT '终态错误机器编码',
    error_message VARCHAR(2000) NULL COMMENT '脱敏后的终态错误摘要',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录最后更新时间',
    created_by VARCHAR(128) NOT NULL DEFAULT 'system:database-migration' COMMENT '记录创建操作者',
    updated_by VARCHAR(128) NOT NULL DEFAULT 'system:database-migration' COMMENT '记录最后更新操作者',
    PRIMARY KEY (id),
    CONSTRAINT uk_manga_creative_run_id UNIQUE (run_id),
    CONSTRAINT uk_manga_creative_run_user_request UNIQUE (user_id, request_id),
    CONSTRAINT uk_manga_creative_run_active_conversation UNIQUE (active_conversation_id),
    CONSTRAINT ck_manga_creative_run_trigger CHECK (trigger_source IN ('CONVERSATION', 'MANUAL')),
    CONSTRAINT ck_manga_creative_run_target_pair CHECK ((target_type IS NULL AND target_id IS NULL) OR (target_type IS NOT NULL AND target_id IS NOT NULL)),
    CONSTRAINT ck_manga_creative_run_entry CHECK (
        (trigger_source = 'CONVERSATION' AND operation_type = 'ASSISTANT_CHAT' AND target_type IS NULL AND target_id IS NULL)
        OR
        (trigger_source = 'MANUAL' AND operation_type <> 'ASSISTANT_CHAT'
            AND target_type IS NOT NULL AND target_id IS NOT NULL)
    ),
    CONSTRAINT ck_manga_creative_run_permission CHECK (permission_policy IN ('READ_ONLY', 'PROPOSE_CHANGES', 'CONFIRM_SIDE_EFFECTS', 'AUTOMATION')),
    CONSTRAINT ck_manga_creative_run_status CHECK (status IN ('QUEUED', 'ACTIVE', 'WAITING', 'CANCEL_REQUESTED', 'COMPLETED', 'FAILED', 'CANCELLED')),
    INDEX idx_manga_creative_run_conversation_status (conversation_id, status, id),
    INDEX idx_manga_creative_run_target_status (project_id, target_type, target_id, operation_type, status),
    INDEX idx_manga_creative_run_user_status_updated (user_id, status, updated_at),
    INDEX idx_manga_creative_run_status_deadline (status, deadline_at),
    INDEX idx_manga_creative_run_lease (status, lease_until),
    CONSTRAINT fk_manga_creative_run_conversation FOREIGN KEY (conversation_id) REFERENCES manga_creative_conversation (conversation_id) ON DELETE SET NULL,
    CONSTRAINT fk_manga_creative_run_user FOREIGN KEY (user_id) REFERENCES manga_user (id) ON DELETE CASCADE,
    CONSTRAINT fk_manga_creative_run_project FOREIGN KEY (project_id) REFERENCES manga_project (id) ON DELETE SET NULL
) COMMENT = 'AI 漫剧创作运行表';

CREATE TABLE manga_creative_event (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '创作事件数据库主键',
    run_id CHAR(36) NOT NULL COMMENT '所属创作运行标识',
    step_id CHAR(36) NULL COMMENT '可选的所属创作步骤标识',
    sequence_no BIGINT NOT NULL COMMENT '运行内严格递增事件序号',
    schema_version INT NOT NULL DEFAULT 1 COMMENT '事件 Envelope Schema 版本',
    event_type VARCHAR(64) NOT NULL COMMENT '稳定事件类型',
    source VARCHAR(128) NOT NULL DEFAULT 'creative/runtime' COMMENT '产生事件的运行时组件或能力',
    correlation_id VARCHAR(128) NULL COMMENT '可选的工具调用、作业或审批关联标识',
    payload_json LONGTEXT NOT NULL COMMENT '脱敏后的结构化事件载荷',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录最后更新时间',
    created_by VARCHAR(128) NOT NULL DEFAULT 'system:database-migration' COMMENT '记录创建操作者',
    updated_by VARCHAR(128) NOT NULL DEFAULT 'system:database-migration' COMMENT '记录最后更新操作者',
    PRIMARY KEY (id),
    CONSTRAINT uk_manga_creative_event_sequence UNIQUE (run_id, sequence_no),
    CONSTRAINT ck_manga_creative_event_schema CHECK (schema_version > 0),
    INDEX idx_manga_creative_event_run_sequence (run_id, sequence_no),
    INDEX idx_manga_creative_event_step_sequence (step_id, sequence_no),
    CONSTRAINT fk_manga_creative_event_run FOREIGN KEY (run_id) REFERENCES manga_creative_run (run_id) ON DELETE CASCADE
) COMMENT = 'AI 漫剧创作事件追加日志表';

CREATE TABLE manga_creative_event_outbox (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '事件出站记录主键',
    run_id CHAR(36) NOT NULL COMMENT '所属创作运行标识',
    sequence_no BIGINT NOT NULL COMMENT '所属事件序号',
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT '投递状态',
    claim_owner VARCHAR(128) NULL COMMENT '当前批量领取实例标识',
    claim_until TIMESTAMP NULL COMMENT '当前批量领取截止时间',
    next_attempt_at TIMESTAMP NULL COMMENT '下一次允许投递时间',
    published_at TIMESTAMP NULL COMMENT '投递完成时间',
    attempts INT NOT NULL DEFAULT 0 COMMENT '累计投递次数',
    last_error VARCHAR(1000) NULL COMMENT '最近一次投递错误摘要',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录最后更新时间',
    created_by VARCHAR(128) NOT NULL DEFAULT 'system:database-migration' COMMENT '记录创建操作者',
    updated_by VARCHAR(128) NOT NULL DEFAULT 'system:database-migration' COMMENT '记录最后更新操作者',
    PRIMARY KEY (id),
    CONSTRAINT uk_manga_creative_event_outbox_event UNIQUE (run_id, sequence_no),
    CONSTRAINT ck_manga_creative_event_outbox_status CHECK (status IN ('PENDING', 'PUBLISHED')),
    INDEX idx_manga_creative_event_outbox_claim (status, next_attempt_at, claim_until, id),
    CONSTRAINT fk_manga_creative_event_outbox_event FOREIGN KEY (run_id, sequence_no) REFERENCES manga_creative_event (run_id, sequence_no) ON DELETE CASCADE
) COMMENT = 'AI 漫剧创作事件投递箱表';
